spring.application.name=registration-system

spring.datasource.url=jdbc:mysql://mysql:3306/otp_auth
spring.datasource.username=root
spring.datasource.password=Pass1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sauravbagade@gmail.com
spring.mail.password=pnai knih dhwn oraz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
